### ISSUE TITLE
Commercial use?

### ISSUE THREAD

**Issue by evolu8** [NVlabs/LITA#1]
will a license be adopted to allow commercial use?

**Comment by daahuang** [comment]
For commercial use of this codebase, please visit [NVIDIA Research Licensing](https://www.nvidia.com/en-us/research/inquiries/). For NVIDIA Vision-Language Models, please also check out [NVIDIA Visual Insight Agent](https://www.nvidia.com/en-eu/solutions/robotics-and-edge-computing/vision-ai/visual-insight-agent/).
