### ISSUE TITLE
Video Data Unavailable: Request for Alternative Access to ActivityNet-Captions or ActivityNet-RTL Datasets

### ISSUE THREAD

**Issue by qirui-chen** [NVlabs/LITA#4]
Thank you for your excellent work. However, the data download links for frames or raw videos on the official ActivityNet-Captions website are no longer working. Could you please provide the video data corresponding to the ActivityNet-Captions or ActivityNet-RTL datasets? Thank you!

**Comment by qirui-chen** [comment]
The videos of Activitynet can be downloaded through this link: https://github.com/activitynet/ActivityNet/issues/57

**Comment by wenzhengzeng** [comment]
Hi, do you know which specific file we should download? After my request, it seems that the official Google Drive link provides many files, but I couldn't find one named 'frames_activitynet_5fps_res_320x240.tar' as the author mentioned. Can you tell me the exact file name? Thank you!

**Comment by qirui-chen** [comment]
It seems my access to the shared links has expired so I do not know the currently provided files. However, I think I have used the raw videos named "[Update]_Anet_videos_15fps_short256.zip". For more detailed information, I recommend reaching out directly to the official ActivityNet repository. I hope this helps.

**Comment by qirui-chen** [comment]
@wenzhengzeng  Hi, it seems that my access to the shared links has expired so I don't know currently available files. However, I think I used the raw videos named "[Update]_Anet_videos_15fps_short256.zip". For more detailed information, I recommend reaching out directly to the official ActivityNet repository. I hope this helps.

**Comment by wenzhengzeng** [comment]
I will try it. Thank you!
